SELECT [NOME] ,[CPF],[ESTADO] 
FROM [TABELA DE CLIENTES]

SELECT * FROM [TABELA DE CLIENTES]

SELECT [NOME] AS [NOME DO CLIENTE],[CPF] AS [CPF DO CLIENTE],[ESTADO] AS [UF] 
FROM [TABELA DE CLIENTES]

SELECT [MATRICULA] AS [IDENTIFICADOR], [NOME] AS [NOME DO VENDEDOR] FROM [VENDEDORES]

SELECT DISTINCT [SABOR] FROM [TABELA DE PRODUTOS]

SELECT [NOME] AS [NOME DO CLIENTE],[PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES] WHERE [PRIMEIRA COMPRA] = 1;

SELECT * FROM [TABELA DE PRODUTOS]
WHERE [PRECO DE LISTA] <= 7.00

SELECT * FROM [TABELA DE PRODUTOS] 
WHERE [EMBALAGEM] > 'Lata'

SELECT [NOME], [DATA DE NASCIMENTO] FROM [TABELA DE CLIENTES]  WHERE YEAR([DATA DE NASCIMENTO]) > '1995'

SELECT [NOME], [BAIRRO] FROM [TABELA DE CLIENTES] WHERE [BAIRRO] = 'Copacabana' OR [BAIRRO] = 'Tijuca'

SELECT [NOME], [ESTADO], [PRIMEIRA COMPRA] FROM [TABELA DE CLIENTES] WHERE [ESTADO] = 'RJ' AND [PRIMEIRA COMPRA] = 1

SELECT [NOME], [PERCENTUAL COMISSAO] FROM [VENDEDORES] WHERE [PERCENTUAL COMISSAO] > 8

SELECT [NOME DO PRODUTO],[PRECO DE LISTA] AS [VALOR], [EMBALAGEM] FROM [TABELA DE PRODUTOS] WHERE [PRECO DE LISTA] < 6.00 AND [EMBALAGEM] = 'Lata'

SELECT [NOME], [ESTADO] FROM [TABELA DE CLIENTES] WHERE [ESTADO] <> 'SP' AND [ESTADO] <> 'RJ'

UPDATE [TABELA DE PRODUTOS]
SET [PRECO DE LISTA] = [PRECO DE LISTA] * 0.9 WHERE [EMBALAGEM] = 'Lata'

UPDATE [TABELA DE PRODUTOS]
SET [EMBALAGEM] = 'Garrafa', [PRECO DE LISTA] = 8.10 WHERE [CODIGO DO PRODUTO] = '1088126'

SELECT * FROM [TABELA DE PRODUTOS]

DELETE FROM [TABELA DE PRODUTOS] WHERE [CODIGO DO PRODUTO] = '1004327'