/* colunas: 
CPF;
Nome completo;
Endereço completo;
Data de nascimento;
Idade;
Sexo;
Limite de credito;
Volume minimo da compra;
Se já realizou alguma compra na empresa;*/
CREATE TABLE [TABELA DE CLIENTES] (
[CPF] [CHAR] (11),
[NOME] [VARCHAR] (100),
[RUA] [VARCHAR] (100),
[COMPLEMENTO] [VARCHAR] (100),
[BAIRRO] [VARCHAR] (100),
[ESTADO] [CHAR] (2),
[CEP] [CHAR] (8),
[DATA DE NASCIMENTO] [DATE],
[IDADE] [SMALLINT],
[SEXO] [CHAR] (1),
[LIMITE DE CREDITO] [MONEY],
[VOLUME MINIMO] [FLOAT],
[PRIMEIRA COMPRA] [BIT],
);

CREATE TABLE [TABELA DE PRODUTOS] (
[CODIGO DO PRODUTO] [VARCHAR] (25) NOT NULL PRIMARY KEY,
[NOME DO PRODUTO] [VARCHAR] (50),
[EMBALAGEM] [VARCHAR] (50),
[TAMANHO] [VARCHAR] (50),
[SABOR] [VARCHAR] (50),
[PRECO DE LISTA] [SMALLMONEY]
)

ALTER TABLE [TABELA DE CLIENTES] ALTER COLUMN [CPF] [CHAR] (11) NOT NULL;

ALTER TABLE [TABELA DE CLIENTES] ADD CONSTRAINT PK_TABELA_CLIENTE
PRIMARY KEY CLUSTERED ([CPF]);

CREATE TABLE [VENDEDORES] (
[MATRICULA] [CHAR] (5) NOT NULL PRIMARY KEY,
[NOME] [VARCHAR] (100) NOT NULL,
[PERCENTUAL COMISSAO] [FLOAT]
);