SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA'

SELECT NOME_DO_PRODUTO, PRECO_DE_LISTA, 
(CASE WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO
FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' ORDER BY PRECO_DE_LISTA


SELECT  
(CASE WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
      ELSE 'PRODUTO BARATO' END) AS CLASSIFICACAO, COUNT (*) AS NUMERO_DE_PRODUTOS
FROM TABELA_DE_PRODUTOS 
GROUP BY (CASE WHEN PRECO_DE_LISTA > 12 THEN 'PRODUTO CARO'
      WHEN PRECO_DE_LISTA >= 7 AND PRECO_DE_LISTA < 12 THEN 'PRODUTO EM CONTA'
      ELSE 'PRODUTO BARATO' END)


SELECT 
(CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE' 
       WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
       ELSE 'CLIENTE PEQUENO' END) AS CLIENTES, COUNT (*) AS CLASSIFICACAO
       FROM TABELA_DE_CLIENTES
       GROUP BY ( CASE WHEN LIMITE_DE_CREDITO >= 150000 THEN 'CLIENTE GRANDE' 
       WHEN LIMITE_DE_CREDITO >= 110000 AND LIMITE_DE_CREDITO < 150000 THEN 'CLIENTE MEDIO'
       ELSE 'CLIENTE PEQUENO' END)


