SELECT * FROM TABELA_DE_CLIENTES

SELECT CIDADE, IDADE FROM TABELA_DE_CLIENTES ORDER BY CIDADE, IDADE

SELECT CIDADE, SUM (IDADE) AS IDADE FROM TABELA_DE_CLIENTES GROUP BY CIDADE

SELECT CIDADE, SUM (IDADE) AS IDADE, SUM (LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE

SELECT CIDADE, AVG (IDADE) AS IDADE, SUM (LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY CIDADE

SELECT CIDADE, COUNT (*) AS NUMERO_DE_CLIENTES FROM TABELA_DE_CLIENTES GROUP BY CIDADE

SELECT ESTADO, MAX(LIMITE_DE_CREDITO) AS CREDITO FROM TABELA_DE_CLIENTES GROUP BY ESTADO

SELECT COUNT (*) AS [QUANTIDADE DE VENDAS] FROM ITENS_NOTAS_FISCAIS WHERE CODIGO_DO_PRODUTO = '1101035' AND QUANTIDADE = 99


