SELECT * FROM TABELA_DE_PRODUTOS
SELECT EMBALAGEM FROM TABELA_DE_PRODUTOS
SELECT DISTINCT EMBALAGEM FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MACA'
SELECT DISTINCT EMBALAGEM, SABOR FROM TABELA_DE_PRODUTOS
SELECT DISTINCT SABOR FROM TABELA_DE_PRODUTOS