SELECT * FROM TABELA_DE_CLIENTES;
SELECT NOME,IDADE FROM TABELA_DE_CLIENTES WHERE IDADE > 25;
SELECT * FROM TABELA_DE_CLIENTES WHERE IDADE < 25;
SELECT * FROM TABELA_DE_CLIENTES WHERE DATA_DE_NASCIMENTO >= '1995-11-14'
SELECT * FROM TABELA_DE_CLIENTES WHERE BAIRRO >= 'LAPA'



SELECT * FROM TABELA_DE_PRODUTOS;
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR = 'MANGA' OR TAMANHO = '470 ml';


SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR IN ('LIMA/LIMAO', 'MORANGO/LIMAO')
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%LIMAO'
SELECT * FROM TABELA_DE_PRODUTOS WHERE SABOR LIKE '%MORANGO%'



